version: 0.2

phases:
  install:
    commands:
      - echo "Upgrade Pip and install packages"
      - pip install --upgrade pip
      - make install
            # create the aws dir
      - mkdir -p ~/.aws/
      # create fake credential file
      - echo "[default]\naws_access_key_id = FakeKey\naws_secret_access_key = FakeKey\naws_session_token = FakeKey" > ~/.aws/credentials

  build:
    commands:
      - echo "Run lint and test"
      - make lint
      #- PYTHONPATH=".";make test
  post_build:
    commands:
      - echo "mounting EFS"
      - apt-get update
      - apt-get install nfs-common --yes
      - mkdir efs
      - mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-1a09cdb3.efs.us-west-2.amazonaws.com:/ efs
      - ls -la /efs